# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UCLhackTravelFun' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UCLhackTravelFun
  pod 'SnapKit', '~> 3.0'
  pod 'Alamofire’, ‘~> 4.0’
  pod 'SwiftGifOrigin', '~> 1.6.1'

  target 'UCLhackTravelFunTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UCLhackTravelFunUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
